packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  typescript: ^5.5.3
  zod: ^3.23.8
  tailwindcss: ^3.4.5

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0